# configmap - pod env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: app
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---  

# Deployment Resource
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  # deployment labels, helps to organize and select resources.
  labels:
    component: cart
    project: roboshop
    tier: app
# Deployment spec     
spec:
  # 1 pod replica
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: database
  # This is pod definition
  template:
    metadata:
      labels:
        component: cart
        project: roboshop
        tier: database
    spec:
      containers:
      - name: cart
        image: gsivadvops/cart:v1
        # refring configmap in container
        envFrom:
        - configMapRef:
            name: cart
---
# service resource used to expose pods
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  # service labels, helps to organize and identify this service
  labels:
    component: cart
    project: roboshop
    tier: app
# service spec 
spec:
  # Matches pods with the same labels (so service knows which pods to send traffic to)
  selector:
    component: cart
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 8080 # service port, what clients use
    targetPort: 8080 # container port inside pod 