# configmap - pod env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---  
# Deployment Resource
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # deployment labels, helps to organize and select resources.
  labels:
    component: shipping
    project: roboshop
    tier: app
# Deployment spec     
spec:
  # 1 pod replica
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
  # This is pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: gsivadvops/shipping:v1
        # refring configmap in container
        envFrom:
        - configMapRef:
            name: shipping
---
# service resource used to expose pods
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  # service labels, helps to organize and identify this service
  labels:
    component: shipping
    project: roboshop
    tier: app
# service spec 
spec:
  # Matches pods with the same labels (so service knows which pods to send traffic to)
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port, what clients use
    targetPort: 8080 # container port inside pod 