# secret for mysql password
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="

---
# Deployment Resource
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # deployment labels, helps to organize and select resources.
  labels:
    component: mysql
    project: roboshop
    tier: database
# Deployment spec     
spec:
  # 1 pod replica
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database
  # This is pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mysql
        image: gsivadvops/mysql:v1
        envFrom:
        - secretRef:
            name: mysql 
---
# service resource used to expose pods
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  # service labels, helps to organize and identify this service
  labels:
    component: mysql
    project: roboshop
    tier: database
# service spec 
spec:
  # Matches pods with the same labels (so service knows which pods to send traffic to)
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306 # service port, what clients use
    targetPort: 3306 # container port inside pod 